# SERVICE.yaml for the `simple-echo-server`
#   by Lut99
# 
# Defines a service file for the simple-echo-server on Kubernetes.
# 
# Tested on v1.23.0.
# 

apiVersion: v1
kind: Service
metadata:
  name: simple-echo-server-service
  labels:
    app: simple-echo-server
spec:
  selector:
    app: simple-echo-server
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
